#pragma once

#include "resource.h"
#define MAX_DIGITS 15

#define CALC_HEIGHT 340
#define CALC_WIDTH 300

#define ROW_GAP 10

#define RESULT_X 1
#define RESULT_Y 1
#define RESULT_HEIGHT 50 
#define RESULT_WIDTH 250

#define BUTTON_ROW_X 50
#define BUTTON_ROW_Y 55
#define BUTTON_HEIGHT 45
#define BUTTON_WIDTH 39

#define IDC_STATIC_RESULT 101
#define IDC_BUTTON_SEVEN 201
#define IDC_BUTTON_EIGHT 202
#define IDC_BUTTON_NINE 203
#define IDC_BUTTON_NEGATIVE 204
#define IDC_BUTTON_DEL 205
#define IDC_BUTTON_FOUR 206
#define IDC_BUTTON_FIVE 207
#define IDC_BUTTON_SIX 208
#define IDC_BUTTON_MULTIPLICATION 209
#define IDC_BUTTON_DIVISION 210
#define IDC_BUTTON_ONE 211
#define IDC_BUTTON_TWO 212
#define IDC_BUTTON_THREE 213
#define IDC_BUTTON_SUBTRACTION 214
#define IDC_BUTTON_EQUAL 215
#define IDC_BUTTON_CLEAR 216
#define IDC_BUTTON_ZERO 217
#define IDC_BUTTON_DECIMAL 218
#define IDC_BUTTON_ADDITION 219

#define ADD 1
#define SUB 2
#define MUL 3
#define DIV 4
#define LEFT 1
#define RIGHT 2

#define IDM_ABOUT 5
#define IDM_A 6
#define IDM_B 7
#define A_KEY 0x41
#define B_KEY 0x42